[package]
name = "server"
version.workspace = true
edition.workspace = true
default-run = "server"

[dependencies]
anyhow.workspace = true
axum.workspace = true
base64.workspace = true
design-model.workspace = true
getrandom.workspace = true
reqwest.workspace = true
schemars.workspace = true
sha2.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
http-body-util.workspace = true
tempfile.workspace = true
tower.workspace = true

[lints]
workspace = true
